//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TI_PROJ_2257
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public Nullable<int> importancia { get; set; }
        public Nullable<int> utilizador { get; set; }
    
        public virtual utilizador utilizador1 { get; set; }
    }
}
